### ISSUE TITLE
OnVideoSinkDecodedSample Decoded video mosaic problem

### ISSUE THREAD

**Issue by Hu-Said** [sipsorcery/SIPSorceryMedia.Encoders#5]
There is a problem when using the VideoEncoderEndPoint class. In relay mode, the video is normal, but in other modes (for example: host), it will always be mosaic. What could be the problem? The following are screenshots of the two situations
![image](https://github.com/sipsorcery-org/SIPSorceryMedia.Encoders/assets/63393002/d1a04d39-ea26-4b96-ac4f-7d8b4f6697c3)
![image](https://github.com/sipsorcery-org/SIPSorceryMedia.Encoders/assets/63393002/f8550b9a-7ce8-46a7-a185-c6f7a0acb132)
![image](https://github.com/sipsorcery-org/SIPSorceryMedia.Encoders/assets/63393002/c043fe26-e4ef-4d92-baa2-330f791d07e2)

**Comment by sipsorcery** [comment]
The first thing to try is to reduce the frame rate and/or resolution and see if the video stream improves.

If so then the problem is most likely packet loss. Video stream are particularly susceptible as they rely on key frames that may only be generated every few seconds and then affect the decoding of all subsequent frames.

**Comment by Hu-Said** [comment]
> The first thing to try is to reduce the frame rate and/or resolution and see if the video stream improves.
> 
> If so then the problem is most likely packet loss. Video stream are particularly susceptible as they rely on key frames that may only be generated every few seconds and then affect the decoding of all subsequent frames.

The current resolution is 240*320, FPS=15. I think this should perform very well. The same resolution is used to send videos on the windows side and receive them in the browser. The performance is good. What I can’t understand the most is Why it performs better in relay mode

**Comment by Hu-Said** [comment]
Okay, I tried it again, and the relay are also mosaic. This has nothing to do with the mode.

**Comment by sipsorcery** [comment]
The only thing I can think of if it works better with a relay peer compared to a host peer is if there's some kind of filter or dodgy route on the direct path between the host peers.

And when you say relay mode you are sure the video stream is going through a TURN server?

**Comment by Hu-Said** [comment]
> The only thing I can think of if it works better with a relay peer compared to a host peer is if there's some kind of filter or dodgy route on the direct path between the host peers.
> 
> And when you say relay mode you are sure the video stream is going through a TURN server?



> Okay, I tried it again, and the relay are also mosaic. This has nothing to do with the mode.

Now I don’t think it has much to do with the connection mode. I don’t know why. The same network, the same mode, the same resolution and frame rate, on Android and Linux, the performance is normal and there is no mosaic, so now I We can only consider whether there is a problem with the decoding.

**Comment by Hu-Said** [comment]
I will use the FFmped library today to see if this happens.

**Comment by Hu-Said** [comment]
> The only thing I can think of if it works better with a relay peer compared to a host peer is if there's some kind of filter or dodgy route on the direct path between the host peers.
> 
> And when you say relay mode you are sure the video stream is going through a TURN server?

Yes, I can confirm that the video stream is going through the TURN service. The current performance is that the relay mode is normal in most cases, and other modes do not perform well. I tried adjusting the resolution, but it had no effect. I really don't understand what the problem could be. Is it a network problem? This doesn't quite convince me.

**Comment by liuxiangyu8** [comment]
I had this Mosaic problem, too
